name: ORExplainer

channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pyg=2.2.0
  - spacy=3.5.2
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - networkx
  - tqdm
  - matplotlib
  - jupyterlab
  - pip
